import {
  ClauseDef,
  DocumentModule,
  FieldDef,
  GenericFormData,
  emptyEntity,
  entityNameText,
  fieldText,
} from "../genericDocument";

const providerName = (data: GenericFormData) => entityNameText(data, "provider", "Provider");
const customerName = (data: GenericFormData) => entityNameText(data, "customer", "Customer");

const AGREEMENT_FIELD: FieldDef = {
  key: "agreement",
  label: "Base Agreement",
  kind: "text",
  hint: "The base commercial agreement (e.g. a Cloud Service Agreement or Software License Agreement) this AI Addendum attaches to",
  inputPlaceholder: "e.g. the Cloud Service Agreement dated January 1, 2026",
};

const TRAINING_DATA_FIELD: FieldDef = {
  key: "trainingData",
  label: "Training Data",
  kind: "textarea",
  hint: "The data Provider may use to train its AI models, if Model Training is permitted",
  fallback: "no Training Data",
};

const TRAINING_PURPOSES_FIELD: FieldDef = {
  key: "trainingPurposes",
  label: "Training Purposes",
  kind: "textarea",
  hint: "The purposes for which Provider may use the Training Data",
  fallback: "no Training Purposes",
};

const TRAINING_RESTRICTIONS_FIELD: FieldDef = {
  key: "trainingRestrictions",
  label: "Training Restrictions",
  kind: "textarea",
  hint: "Any restrictions on Provider's use of the Training Data for the Training Purposes",
  fallback: "no additional restrictions",
};

const IMPROVEMENT_RESTRICTIONS_FIELD: FieldDef = {
  key: "improvementRestrictions",
  label: "Improvement Restrictions",
  kind: "textarea",
  hint: "Any restrictions on Provider's use of Input, Output, and Training Data to otherwise maintain, develop, and improve the AI System outside of Training",
  fallback: "no additional restrictions",
};

const clauses: ClauseDef[] = [
  {
    number: 1,
    title: "AI Services",
    body: (d) =>
      `The AI Services are part of the Product and are subject to ${fieldText(d, AGREEMENT_FIELD)} as supplemented by this AI Addendum. ${customerName(d)} may use the AI Services by providing Input, and the AI Services may generate Output in response to that Input. ${providerName(d)} may copy, display, modify, distribute, and use Input to the extent necessary to provide the AI Services, and ${customerName(d)} authorizes ${providerName(d)} to process Input for those purposes. Without limiting the restrictions in ${fieldText(d, AGREEMENT_FIELD)}, ${customerName(d)} will not, and will not allow anyone else to, use the AI Services for decision-making in a regulated industry or capacity without proper human oversight and review in compliance with applicable law and applicable professional ethics, guidelines, and rules; use the AI Services to violate, misappropriate, or otherwise infringe the intellectual property or other proprietary rights of others; or falsely state that Output was created by a human. Unless the parties have identified Training Data (${fieldText(d, TRAINING_DATA_FIELD)}) and Training Purposes (${fieldText(d, TRAINING_PURPOSES_FIELD)}), ${providerName(d)} may not use ${customerName(d)}'s Input or Output to Train any Model. Where Training is permitted, ${providerName(d)} may copy, modify, distribute, and use the Training Data for the Training Purposes, subject to these Training Restrictions: ${fieldText(d, TRAINING_RESTRICTIONS_FIELD)}. Subject to these Improvement Restrictions (${fieldText(d, IMPROVEMENT_RESTRICTIONS_FIELD)}), ${providerName(d)} may otherwise use Input, Output, and Training Data to provide, maintain, develop, and improve the AI System, so long as that use does not constitute Training except to the extent authorized for the Training Purposes above.`,
  },
  {
    number: 2,
    title: "Intellectual Property and Privacy",
    body: (d) =>
      `As between the parties, ${customerName(d)} retains all right, title, and interest in and to all Input and owns all Output; to the extent permitted by applicable law, ${providerName(d)} hereby assigns to ${customerName(d)} all right, title, and interest, if any, in and to Output. Nothing in this AI Addendum reduces or limits ${providerName(d)}'s obligations under applicable data protection laws regarding Personal Data that may be contained in Input. ${customerName(d)} represents and warrants that it, its Users, and anyone submitting Input on its behalf have, and will continue to have, all rights necessary to submit that Input to the AI Services.`,
  },
  {
    number: 3,
    title: "Disclaimers",
    body: (d) =>
      `Due to the nature of artificial intelligence and machine learning, information generated by the AI Services may be incorrect or inaccurate; the AI Services are not human and are not a substitute for human oversight, and Output generated by the AI Services may not be protectable as intellectual property. Output may also resemble or be duplicative of data, information, and materials the AI Services generate for others, and ${providerName(d)} does not represent or warrant that Output does not and will not incorporate or reflect the data, information, prompts, or materials of others, will not violate, misappropriate, or otherwise infringe the intellectual property or other proprietary rights of another person or entity, or will not be reproduced in the same or similar way for another user of the AI Services.`,
  },
];

export const aiAddendumModule: DocumentModule = {
  id: "ai-addendum",
  title: "AI Addendum",
  pdfFilename: "AI-Addendum.pdf",
  fields: [
    AGREEMENT_FIELD,
    TRAINING_DATA_FIELD,
    TRAINING_PURPOSES_FIELD,
    TRAINING_RESTRICTIONS_FIELD,
    IMPROVEMENT_RESTRICTIONS_FIELD,
  ],
  entities: [
    { key: "provider", roleLabel: "Provider" },
    { key: "customer", roleLabel: "Customer" },
  ],
  defaultData: () => ({
    values: {
      agreement: "",
      trainingData: "",
      trainingPurposes: "",
      trainingRestrictions: "",
      improvementRestrictions: "",
    },
    entities: {
      provider: emptyEntity(),
      customer: emptyEntity(),
    },
  }),
  clauses,
};
